name: ConsolePlayerExecutor
version: '${project.version}'
main: dev.timecoding.consoleplayerexecutor.ConsolePlayerExecutor
api-version: 1.19
authors: [ TimeCoding ]
description: Execute a player only command from the console!
website: timecoding.de

commands:
  executeas:
    description: "This command allows to execute commands from the console as a player!"
    aliases:
      - executeasplayer

